ignore:
  - "curriculos/base/migrations/*" # ignore folders and all its contents
  - "curriculos/base/models.py"
  - "curriculos/base/asgi.py"
  - "curriculos/base/admin.py"
  - "curriculos/base/settings.py"
  - "curriculos/cadastro/migrations/*" # ignore folders and all its contents
  - "curriculos/cadastro/models.py"
  - "curriculos/cadastro/admin.py"
  - "curriculos/asgi.py"
  - "curriculos/wsgi.py"

