version: "3.3"

services:
  database:
    container_name: curriculos_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres_curriculos
      - POSTGRES_USER=postgres
    ports:
      - 5435:5432
