# Generated by Django 3.2 on 2021-04-22 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(default='(00)000-000-000', max_length=20)),
                ('formacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.formacao')),
            ],
        ),
    ]
