# Generated by Django 3.2 on 2021-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('creation', models.DateField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
