# Generated by Django 3.2 on 2021-04-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]
    

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='formacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.formacao'),
        ),
    ]
