# Generated by Django 3.2 on 2021-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoa_telefone'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
