name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:13.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Copiar template de configuração do decouple
      run: cp contrib/env-sample .env

    - name: Install dependencies with pipenv
      run: |
          pip install pipenv
          pipenv install --deploy --dev
    - run: pipenv run flake8


    - name: Criando o banco para teste
      run: psql -c "CREATE DATABASE testdb;" -U postgres


    - name: Execução dos testes
      run: pipenv run pytest -v --cov=curriculos

    - name: Posting Coverage
      env:
        super_secret: ${{ secrets.CODECOV_TOKEN }}
      run: pipenv run codecov
